# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bridget Kate Cowie
email: bridgetkcowie@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Witty descriptions are not my forte, so for now dear reader
  please assume that this site will provide you information
  about me (blog posts & other assorted information).
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: bridgetkcowie
github_username:  iambridgetkate
facebook_username: bridgetkcowie
linkedin_username: bridgetcowie
email_address: bridgetkcowie@gmail.com

# Build settings
markdown: kramdown
